"""
gen_supabase_seed.py
--------------------
Reads producers.csv and emits supabase/seed_producers.sql - a set of
idempotent INSERT statements that seed the public.producers table.

Run:
  python data-prep/gen_supabase_seed.py
Then paste supabase/seed_producers.sql into the Supabase SQL editor and Run.
"""

import csv
from pathlib import Path

CSV_FILE = Path(__file__).parent / 'producers.csv'
OUT_FILE = Path(__file__).parent.parent / 'supabase' / 'seed_producers.sql'


def sql_str(v: str) -> str:
    """Quote a string for SQL, or NULL if empty."""
    v = (v or '').strip()
    if not v:
        return 'null'
    return "'" + v.replace("'", "''") + "'"


def sql_num(v: str) -> str:
    v = (v or '').strip()
    return v if v else 'null'


def main():
    with open(CSV_FILE, newline='', encoding='utf-8') as f:
        rows = list(csv.DictReader(f))

    lines = [
        '-- Auto-generated by data-prep/gen_supabase_seed.py - do not edit by hand.',
        '-- Seeds public.producers. Re-runnable: existing names are left untouched.',
        '',
        'insert into public.producers (name, commune, docg, lat, lon, website) values',
    ]
    values = []
    for r in rows:
        values.append(
            f"  ({sql_str(r['name'])}, {sql_str(r['commune'])}, "
            f"{sql_str(r['docg'])}, {sql_num(r['lat'])}, {sql_num(r['lon'])}, "
            f"{sql_str(r['website'])})"
        )
    lines.append(',\n'.join(values))
    lines.append('on conflict (name) do nothing;')

    OUT_FILE.parent.mkdir(parents=True, exist_ok=True)
    OUT_FILE.write_text('\n'.join(lines) + '\n', encoding='utf-8')
    print(f'Wrote {len(rows)} producer seed rows -> {OUT_FILE}')


if __name__ == '__main__':
    main()
